### ISSUE TITLE
Ensure proper error logging for WebSocket SubscriptionListeners

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver#111]
By default, the `TypedSubscriptionListener<T>` overrides most interface methods with an empty body.
Especially in the case of `onFailure` and `onError` this should be improved to log the failure reason and its stack trace in any case.

**Comment by martin-fleck-at** [comment]
The problem became obvious while we were using a Java client with a model subscription but missed to register the `ChangePackage` on the client. On the server we used the `RecordingModelResourceManager` which also serializes the recorded changes (field `changeDescription`) as part of the incremental update but the client did not know how to create a resource for that. The fix was easy (registering the ChangePackage) but the error was hard to find as the `onFailure` method was simply empty.

In general I believe it might be also a good idea to add the registration of the ChangePackage to the Java client, either in the subscription listener or somewhere else. What do you think?
