### ISSUE TITLE
Introduce file watching concept

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver#115]
At the moment, if resources are manipulated without direct Model Server requests (regardless of which clients are using ite.g. directly via the file system or via Theia's default editors), the Model Server is not aware of such file manipulations.
We should introduce a file/directory watching concept directly on the Model Server and have a strategy for reconciling (Essentially: either keep the in-memory model and ignore file-system changes, or reload from file system).

(Issue was initially created in `emfcloud-modelserver-theia`: https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/50)

**Comment by debovema** [comment]
Surely a must-have feature IMHO (thinking of the diagrams of the Coffee Editor updating automatically while modifying the text-based model 🙄).
In the meantime, is there an API method to manually reload the models (without reconciliation) ?
If no, wouldn't it be the first feature to implement ?

**Comment by ndoschek** [comment]
Unfortunately we have no implemented feature yet, but I agree this would be first step in this story. We have an open issue addressing that already (#99)

**Comment by vhemery** [comment]
I haven't had the courage to implement the "ask the user" strategy.
To be honest, I don't know whether it is possible to use the websocket connection to ask the user and wait for the answer, or whether we should just warn the end user with the websocket connection, then wait for him to ask for a reload. (with a notification action in Theia)

Anyway, this can come later and the contribution is already consistent by itself, choosing a default reconciliation strategy with Guice.
ReconcilingStrategy.Ignore is the historic behavior, whereas ReconcilingStrategy.AlwaysReload should meet the new expectations.

@debovema 
> 
> 
> Surely a must-have feature IMHO (thinking of the diagrams of the Coffee Editor updating automatically while modifying the text-based model 🙄). In the meantime, is there an API method to manually reload the models (without reconciliation) ? If no, wouldn't it be the first feature to implement ?

If you are modifying the text-based model, you should not need this feature, since the text-based LSP editor should rely itself on the model server model. (see https://www.youtube.com/watch?v=yxS-Xsx-4Tw about the "single source of truth")
On the other hand, if the text file is edited outside the model server, or the file is deleted/renamed, this feature detects it and tries and reconcile the model.
