### ISSUE TITLE
Model URIs returned by ModelServer are inconsistent between "/api/v1/models" and "/api/v1/modeluris".

### ISSUE THREAD

**Issue by hoelzl-florian** [eclipse-emfcloud/emfcloud-modelserver#116]
Assume the workspace is in "/home/workspace" and there is a model file "emfmodel.xyz", then calling model server's
"api/v1/models" and "api/v1/modeluris" query result in inconsistent answer. The former returns "file:/home/workspace/emfmodel.xyz", while the latter returns only "emfmodel.xyz".

My use-case is to use the latter query to efficiently get all models on the server and then selectively query the model
server for the details of each of those models.
This is currently not possible, since the "/home/workspace" part cannot be deduced in any way.

**Comment by martin-fleck-at** [comment]
Hi @hoelzl-florian ,

You are right in the fact that the two methods report the URI in a different way which is something that should probably be fixed. However, I am wondering why this prevents you from performing any queries. Do you have any examples? We do have an adaption in place that should allow you to either provide the workspace-relative URI (as reported by `modeluris`) or the full path (as reported by `models`), see the [adaptation in the default resource manager](https://github.com/eclipse-emfcloud/emfcloud-modelserver/blob/7d7368f1c8a43564e8bc7110e805534a20173f3c/bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java#L413). However, there might be some issues that prevent it to work on all platforms, so maybe you can see whether you can adapt that in your server in the meantime? Alternatively, you simply can override the `getModelUris` method in the [default model controller](https://github.com/eclipse-emfcloud/emfcloud-modelserver/blob/c62bcea4092db4ceac2a398a93041b26cecdaf9e/bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelController.java#L244) by using `getAbsoluteModelUris()` instead of `getRelativeModelUris()`.

**Comment by ndoschek** [comment]
Hi @hoelzl-florian,
this was resolved in ModelServer `v2`, here we resolve modelUris properly and equally for all reqeusts.
As we plan to deprecate `v1` at some point, I will close this issue, if you are still facing issues, please feel free to open a new issue, thank you!
