### ISSUE TITLE
Improve extensibility of model server formats and codecs

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#60]
As reported on [Spectrum](https://spectrum.chat/emfcloud/modelserver/overriding-codecs-in-the-model-server-for-id-encoding~6717c5a3-9397-4f46-add8-b479a6efd4f6), the model server does not provide any way to add custom codecs or replace existing ones. The main reason for this is that we have a single `Codecs` class that has the two by-default supported formats (XMI, JSON) hard-coded.

The goal of this task it to improve on that situation by allowing the user to register/bind new codecs or replace existing ones. 

As a suggestion: Make the codecs configurable with DI:
- Support binding codecs using their interface in the the `ModelServerModule`. For this the interface could be enhanced with the extension/format the codec handles and a priority if necessary. It should be easily possible to register multiple codecs. The `DefaultModelServerModule` should at least bind the two default codecs.
- Add a binding for a manager (CompoundCodec, CodecManager or something similar) that reads out the list of bound codecs and offers query methods similar to what the `Codecs` class offers now. The manager is then injected where necessary but might also be overwritten/rebound in a custom module.

**Comment by vhemery** [comment]
In the submitted PR, the Codecs class keeps a backward compatibility, because I am afraid it may be used by Model Server users.
So I've kept the Codecs class and do not offer the possibility to easily override it.

The codecs and formats can be easily overridden in ModelServerModule with a map, and also a String for telling the preferred format. (explained in javadoc)

The Codecs manager class is now intended to be injected, and its default constructor is now deprecated, only kept for legacy behavior.


I, Vincent HEMERY, have the authorization of my employer, CS GROUP, to make this contribution under the appropriate licenses conditions.

**Comment by martin-fleck-at** [comment]
Thank you for your change, I merged it and we can consider this issue closed.

**Comment by vhemery** [comment]
Thank you @martin-fleck-at for your implication and open-minded spirit.
