### ISSUE TITLE
Absolute full path as modelURI causes error

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver#72]
Using an absolute full path like `file:///home/destination/file.coffee` leads to the following error:

```
9765 [qtp1598898814-26] DEBUG DefaultModelResourceManager  - Could not load resource with URI: file:///home/nina/Clients/OpenSource/emfcloud/emfcloud-modelserver/examples/org.eclipse.emfcloud.modelserver.example/.temp/workspace/SuperBrewer3000.coffee
[qtp1598898814-26] WARN io.javalin.Javalin - Uncaught exception
java.lang.NullPointerException
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.removeResource(DefaultModelResourceManager.java:194)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.removeResourceSafe(DefaultModelResourceManager.java:186)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.loadResource(DefaultModelResourceManager.java:178)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelResourceManager.loadResource(DefaultModelResourceManager.java:165)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelRepository.getModel(ModelRepository.java:59)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelController.getOne(ModelController.java:106)
...
```

**Comment by vhemery** [comment]
@ndoschek Sorry, but it looks like this issue fixed absolute path for linux but broke it for windows.
In org.eclipse.emfcloud.modelserver.emf.common.ModelServerRouting.adaptModelUri(String), `uri.toString()` used to work well for me. But now, `URI.createFileURI(uri.path()).toString();` gets rid of my device part of the path and gives me 404 errors. ( https://github.com/eclipse-emfcloud/emfcloud-modelserver/commit/b1eb06f5c36f0abe77f953aa030603449c17e95f )

Here is what my uri looks like and the various values of interest.
![image](https://user-images.githubusercontent.com/7920847/108193734-10ccab80-7116-11eb-9b65-083477c0fb43.png)
Maybe using `devicePath` or `toFileString` method ? Though I guess the issue would still be here because I have a blank authority...

I'm not sure what's the best fix here working for both linux and windows. Could you try and adapt this method to work with both URI patterns ?
Thanks in advance.

**Comment by vhemery** [comment]
After second though, I'm also concerned with what may happen to non-file URIs... like a platform:/resource/ URI (which is absolute).
Maybe it would be best to delegate this adaptModelUri method to the ModelResourceManager, so that we can adapt it taking all the known supported schemes instead of this private scope-limited method...
I may try a PR on this, but I would need someone with a linux to review it so that the adaptModelUri method works as expected on both linux and windows.

**Comment by vhemery** [comment]
Please review https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/80 to ensure it is compatible with the linux use case.

**Comment by ndoschek** [comment]
Thank you very much for raising the issue, I'm sorry I didn't think of the windows use case here.
Also a big thanks for providing a solution so quickly, I will look right into it!
