### ISSUE TITLE
Add support for custom command

### ISSUE THREAD

**Issue by martin-fleck-at** [eclipse-emfcloud/emfcloud-modelserver#78]
At the moment the list of supported commands is fixed in the `Command.ecore` metamodel. If a client sends a command matching one of the classes, it will be decoded into an EMF command, executed on the command stack and finally sent as Json or XMI to the clients as incremental update.

For some languages, however, it might be useful to integrate their own commands. At the moment this is only possible by extending the metamodel and providing a custom CommandCodec that translates the CCommand to an EMF command. The goal of this task is therefore to provide a generic "custom command" in our `Command.ecore` that holds a map of key-value pairs that can be interpreted by the specific languages. Additionally, a use case for such a command should be added to our example.

**Comment by vhemery** [comment]
Just to let you know I've been there and done that (extending the command metamodel and provide new CommandCodec).
My approach was to use the COMPOUND value of CommandKind, then add a secondary attribute for my new command types.
My CommandCodec then translates the command correctly to my own RecordingCommand implementations.

My main concern while doing this was the CommandKind enum which is not extensible and the need to add my own secondary command kind attribute. I've not used it yet on the web client though, only with unit tests on REST directly.

I'm afraid the generic "custom command" may be difficult to build for some complex commands, so the need to extend the command metamodel won't disappear.
Maybe changing the CommandKind enum to a custom EDataType would help. EDataType is much more configurable and you can dynamicaly set the enum values with `ExtendedMetaData.INSTANCE.setEnumerationFacet(enumType, newValues);` (on the same principle as https://eclipsesource.com/blogs/2014/08/26/emf-validation-for-datatype-constraints/ ). So this may be the key to making the command framework more extensible while keeping the internal default values well known...

**Comment by martin-fleck-at** [comment]
@vhemery Thank you for your insight! We are now in the process of providing something like that. We decided to use 'String' for the command type and provide some constants directly in the code instead of working with a custom data type that needs to be extended afterwards. Furthermore, clients shall be able to register the codec for their command type via dependency injection. Furthermore, we believe it might make sense to switch to a transactional domain to be safer with our changes and make use of things like RecordingCommand. 

Do you see any problems with that regarding your own use case? Besides some API breaks of course ;-)

There are still quite some issues to be solved but the general direction we are going can already be seen in the following WIP PR: https://github.com/eclipse-emfcloud/emfcloud-modelserver/pull/84

**Comment by vhemery** [comment]
Actually, in my use case, I had to override some of the methods you refactored to make them compatible with the transactional editing domain (ModelRepository.addTemporaryCommandResource to be more accurate).
So of course, I'll have to adapt the code, but using a transactional editing domain is what I intended all along.

I'm wondering whether some people might want not to use a transfactional editing domain. But in my experience, transactional editing domain provide more reliability in the command management (no more erroneous undo) and are necessary in many cases (like CDO compatibility).
So I tend to think that users who don't use a transactional editing domain do it because it's what the default generated Eclipse EMF editor does, and that they don't really bother in the end...

If we make the use of transactional editing domain mandatory, that's probably something which should be highlighted on the general documentation (main README.md) with a little explanation. Something like
>The use of an EMF transactional editing domain on the server side gives us several advantages. Transactional editing domain allow us to manage the command stack in a more reliable way, the use of transaction providing a clear separation between the end user's operations. This allso release custom command implementers from the burden of implementing the undo behavior of the commands, since the use of a org.eclipse.emf.transaction.RecordingCommand takes it automatically in charge. Finally, transactions allow for the surveillance of individual object changes, enabling the full potential of the EMF validation framework for LIVE validation preventing local modeling errors by the end-user.

I think there is a flaw on how the model server currently handles LIVE validation ( https://spectrum.chat/emfcloud/modelserver/does-model-server-support-emf-constraint-validation~4e3b41b7-aaf9-40ca-a509-bdc15f1966c8?m=MTYxMzk5Mjc5NTQ4Mw== ) and I will most probably make a PR for that, and to be able to get errors from live validation on the client side. (but that's another story)
